# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1bb749f43aa4b82421671153edf1eaf1"
application_url = "https://lou-filters-tampa-auckland.trycloudflare.com"
embedded = true
name = "mayos-test"
handle = "mayos-test"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://lou-filters-tampa-auckland.trycloudflare.com/auth/callback",
  "https://lou-filters-tampa-auckland.trycloudflare.com/auth/shopify/callback",
  "https://lou-filters-tampa-auckland.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
